name: dotnet-desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore PomodoroTimer.sln

    - name: Build
      run: dotnet build PomodoroTimer.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test PomodoroTimer.Tests/PomodoroTimer.Tests.csproj --configuration Release --no-build
